### ISSUE TITLE
Github updates and Entity structure

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#28]
Hi,

We are new developers of Render in Valencia.

We are in doubt whether we can update code directly on Github or if all updates are done via pull request.

Once this is resolved, we also have the doubt if the changes that we are making in the structure of the different entities that we manage and that only affect the Database, without modifying any Dedalo source code file, should be reflected in Github in the dd_copy.sql file of install/import/hierarchy/dd_sql.gz that we have seen that includes information on the structure of different entities that we manage but that we cannot generate because it also contains information on entities that we do not manage. In the event that this file has to be modified, how would we do it? Do we have to tell you what we are modifying so that you reflect it?

And finally, once Dedalo is installed and the DB found in install/db/dedalo4_install.backup is restored, is it possible to load the structure of a certain entity, such as mupreva or muvaet, to display its menus and custom tabs? Or for this it would be necessary to restore the copy of the DB of that specific entity?

Thanks in advance

**Comment by renderpci** [comment]
Hi Pricua and welcome.

Please don't change the dd-sql file, this file will be updated with regularity with the last changes in the official ontology, and yes, it's the full Dédalo ontology with all tlds, normally you will need use only one part of the ontology and you are free to import and change it in your installation.

**Changing the ontology** 

You have two different ways to use/change the Dédalo ontology.

1.  By my own: If you want build your own ontology you don't need add your changes here, but your changes will be incompatible with the official ontology.
2. Sharing changes: If you want to be compatible with the standard sections of the ontology, you will need to publish your changes, in this case, you can use the tld to identify the ontology terms and create the file with the tld name (like mht.sql.gz) in: /install/import/ontology/

In the second case we have two different scenarios:
- a: if the changes are in private or institution tld, your changes will be incorporated into the official ontology by the time (when the ontology file is updated).
- b: if your changes are in the standard tlds, they will need to be approved before. this is because the standard tlds are used by some institutions and projects, and you can't change them without affecting to others users.

The ontology file, with the changes of the specific tld , will include ONLY the data of specific tld of the tables:
-jer_dd (sql file without user, role or id column)
-matrix_descriptors_dd (sql file without user, role or id column)
-matrix_counter_dd (sql file without user, role or id column)

Only one tld for file is allowed. All files with more that one tld will be rejected.

And finally, you can import the ontology in the way that you want, full or by tld, if you want a specific tld use it for change the SQL import script.

Best

**Comment by pricua** [comment]
Hi renderpci,

thanks for the answer. We already have this something clearer.

Being this way, in the next few days we will upload the updated files with the latest changes for you to incorporate into dd_sql.

Regards
