### ISSUE TITLE
Publications (rsc205) - Import from marc21

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#35]
Hi,

We are having problems using the marc21 import from the publications tab (rsc205)

We hadn't used it yet so we don't know if it ever worked or never really worked.

We have tested it in several Dedalo installations, even in a new and clean installation, copying the pear/FILE/MARC.php library, but the error occurs in all of them.

If we try to import the whole file with the mrc extension we get an error when importing.

If we modify the mrc file and leave only one record (<record> tag), the import does finish correctly but a new record is created in publications (rsc205) without any information, with all fields blank.

We were also going to test the version you have at https://dedalo.render.es/dedalo to see if it worked there but we have seen that the import from marc21 does not appear. There are only the options to import Zotero and BIBtex.

We also have evidence that a long time ago in a Dedalo project in Barcelona it was being used correctly.

Is it still working? Do I need to do any additional configuration to make it work?

Thanks and regards

**Comment by renderpci** [comment]
Hi Pricua

Well, the Marc21 import tool, is not full Marc21 implementation, the standard is too big and we only implemented some common fields.

Dédalo is not a Library management system, is a Cultural Heritage management system and we use the import for get some articles or books from other systems, to create bibliographic references inside Dédalo. But we don't want to follow this "old" standard because the work to implemented all fields and specifications would get lot of effort, for get titles, authors, dates of publication and very few more «interesting fields» that Dédalo projects needs.

The tool works, (like you say it's using in some institutions) but you will need to see which fields and marks codes the library records you want import were used by the librarians, and adapt these fields to the Dédalo components. I'm not expert in Marc21 but I know that you can get authors from lots of fields in Marc21; director, primary, secundary, etc. In Dédalo we have only 1 component for all these authors (rsc139) and you need to map all the references used for the authors to this component...

If you want to know about Marc21 you can see the standard here:

https://www.loc.gov/marc/bibliographic/

And if you extend the current implementation, please share it.

I hope that you can import the file...

**Comment by pricua** [comment]
Hi renderpci,

Thanks for the info.

One last thing. Do you have a list of the fields that can currently be imported or a matching relationship between the MARC21 fields and the Dedalo fields?

And do you have or could you send me a MARC21 file that is imported correctly to compare it and do some tests?

Thanks a lot

**Comment by renderpci** [comment]
Hi Pricua

You can see the configuration in:

> ` dedalo/tools/tool_import_marc21/data/tool_import_marc21.php`

I think the code is very clear.

I can't send to you data from other projects... sorry, we signing a privacy contract with this institutions that prohibits us from doing this kind of thing.

I hope that you can import your data.

Best
