### ISSUE TITLE
Automatic Translation of Interviews

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#36]
The "Automatic Translation" option in the "Interview Translation" tool does not work for us. The "Copy to destination" option does work and copies the content of the "Source language" box into the "Target language" box, but the "Automatic translation" option after a waiting time ends without adding any content in "Target language" and without returning any error in the logs or in the console.

This functionality had previously been used successfully in more than 60 interviews.

The value of DEDALO_TRANSLATOR_URL was 'http://babel.antropolis.net/babel/'. We have updated it to 'http://babel.antropolis.net/babel_engine/' (as in the sample.config4.php file) but the behavior is the same.

We have also tried a "clean" installation of Dedalo with the same result.

We see that in the demo of https://dedalo.render.es/dedalo it does work correctly so it seems that there is something that escapes us. Maybe the url of the translation tool could have been changed or something like that.

Let's see if you can give us some light...

Thanks in advance

**Comment by renderpci** [comment]
Hi Pricua

Ohhhh, the old babel.antropolis.net project... well, it's a very sad history, it close some time ago because the project din't get any financial support or aid....

It was a very exited project for build a open and free machine translation, with very good policies for the data and honest about privacy, it was prefect for translating interviews. We use it for long time before it was shut down. It's a pity. 

Now we get by with others translation machines... normally it has per word fare or the policies are not adequate to the data...

So, you can use any other machine translation that you want... 

Best

**Comment by pricua** [comment]
Hello again @renderpci ,

I see that you have already closed the issue but for not opening another and taking advantage of this since the matter is related, I write here.

In the end we have managed to make the automatic translation work using the free automatic translation that Dedalo has on babel.render.es, as indicated in https://dedalo.dev/process_audiovisual_translation. But it has worked for a short time. Now the invocation to the translation service returns the error "Sorry. Quota exceeded. Please contact your service provider."

What is the quota allowed in translations x time? Is it possible to expand or reestablish it in some way, or is it reestablished automatically after a while?

Best

**Comment by pricua** [comment]
Hi,
Understood, all clear then. 

It is not for development tasks. It is for use in a final installation. In that case we will use another machine translation.

Thanks again for the help. You can close the issue.

Best.
