### ISSUE TITLE
Errors with precompiled software in Dedalo 5.8.3n

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#45]
Hi

When I log for the first time with de admin user, I get errors with three software libraries that are alredy precompiled in Dedalo.
Yo can see the errors in the atached pdf

[ERRORS LOGIN ADMIN.pdf](https://github.com/renderpci/dedalo/files/7800531/ERRORS.LOGIN.ADMIN.pdf)

We have another problem with the backup and trying to update de structure. The backup is 0.0 Bytes

<img width="1466" alt="Actualizar estructura" src="https://user-images.githubusercontent.com/38144118/147901970-c3df284e-2364-46fe-ba34-c16d8984995b.PNG">

Help, please.
Thank you very much.

**Comment by renderpci** [comment]
Hi FelipeBergua

**Backup and the ontology update:**
If you read the error in the admin_tool, you can see that the problem is with the pgpass file; _"if you are using pgpass, check config, owner and permissions"_. Well, seems that the pgpass is misconfigured!  ;-)

You can read about how work this file, and how to config postgreSQL pgpass here: https://www.postgresql.org/docs/12/libpq-pgpass.html

The error comes when Dédalo try to run `pg_dump` and it can't run because the process can't access to the database.

Basically, you will need to create a file named `.pgpass` in the /home directory of the php user with the access to the database and set the permissions to the file in this way:

```
chown my_php_user /home/my_php_user/.pgpass
chgrp my_group /home/my_php_user/.pgpass
chmod 600 /home/my_php_user/.pgpass
```

**For the errors in the libraries:**
The first error say that `/lib/tinymce/js/tinymce/tinymce.min.js` is not found, so maybe you need to review if the libraries are installed in the correct path and if the permissions are right.

The path for the libraries are:
`../httpdocs/dedalo/lib/`

Specifically for you installation (I see that you have this path in the errors pdf):
`/var/www/dedalo/lib`

So for the libraries and for tinnymce it would be:
`/var/www/dedalo/lib/tinymce/js/tinymce/tinymce.min.js`

If you don't have the libraries, you can download all precompiled libraries from GitHub, here:
https://github.com/renderpci/dedalo/tree/master/lib

Other possibility is that you apache virtualHosts DocumentRoot property is pointed to the `dedalo` directory instead the `../httpdocs` directory. In you installation the DocumentRoot need to be pointed to `/var/www/`.
All the paths in Dédalo are referenced to the top "dedalo" directory and it need to be accesible by the http requests. For ex:

Wrong version (I see this in the screen capture of the tool_config):
`http://dedalo.wondercoins.es/lib/dedalo`

Correct version:
`http://dedalo.wondercoins.es/dedalo/lib/dedalo`

NOTE: Why? Well, in the V4, V5 Dédalo is installed as other lib, at the same level than TinnyMCE, this config has some advantages to create paths inside de app and change the relative paths to it, but this config it's could be confuse and now this model was changed in the V6 (in beta process) that has more consistent and clear model, `dedalo` directory in `lib` will be change to `core` directory outside the `lib` directory and the work path for `dedalo` in V6 version will be:
`http://dedalo.wondercoins.es/dedalo/lib/core`
https://github.com/renderpci/dedalo/tree/v6_developer

I hope that it can help you.

Best
