### ISSUE TITLE
Does Dédalo have 'templates' depending on the collection?

### ISSUE THREAD

**Issue by jgomcat** [renderpci/dedalo#47]
Hi,

I use Omeka to manage heritage collections and depending on the collection I use one template or another. That is, a heritage collection differs from a scientific-technical collection and therefore the required fields are different in both.

As I see, there is only one template. I know that fields can be added or removed in the only template that exists but it is not what I am looking for.

The question is if we can use different templates in Dédalo depending on the collection.

![3 -Ficha_inventario](https://user-images.githubusercontent.com/97663934/152977747-4323a43d-4806-4db4-bfd9-612243fb90ea.jpg)

Thanks.

**Comment by renderpci** [comment]
Hi jgomcat

If I understand your question, the answer is: Yes, Dédalo has ontologies for different types of heritage. You can install the ontology that you want. If you want you can see our ontology section in our website, here you can see the ISAD(g) ontology for work with documentation heritage:

<img width="1146" alt="Screenshot 2022-02-12 at 08 54 43" src="https://user-images.githubusercontent.com/8447635/153702734-6826497a-4718-4893-b4a1-e56a61fbace1.png">

Or if you want catalog numismatic heritage you can use the "numisdata" ontology:

<img width="1328" alt="Screenshot 2022-02-12 at 08 55 13" src="https://user-images.githubusercontent.com/8447635/153702757-81743915-88d2-43af-9549-de5f73cd21b3.png">

In your screenshot I see that you are showing the ontology of "qdp" for import old data of ethnological heritage, this section is not use to do a catalogue by itself. You can see in the menu that this section is inside "historical" that indicate that is to upload historical data of the catalog, for import data that provide old catalogues in FileMaker, Access, or something like that. Don't use it to create a catalog.

<img width="802" alt="Screenshot 2022-02-12 at 09 02 23" src="https://user-images.githubusercontent.com/8447635/153702890-f59d0027-9d74-47c0-ac4b-8f609b08f34a.png">

If you want to work with the correct section it will be "catalogue":

<img width="607" alt="Screenshot 2022-02-12 at 09 04 50" src="https://user-images.githubusercontent.com/8447635/153702939-cb834815-abc4-409a-9d1b-42dac73eff85.png">

For import ontologies you will need to change your config4.php file to include the ontology that you want.
you have the documentation here: https://dedalo.dev/v5_config#dd1100_730

the var to change is: DEDALO_PREFIX_TIPOS

Last but not least, you can change the ontology by you own, but in these case you need create to own tld, don't change the tld's that exist in the hierarchy section, they are use for other installations and if you change the common section as resources you will not update the ontology because you will not compatible, is better that you propose changes of the common ontologies. Finally, if you want go by your own, I recommend that you open your ontology and share it to all of us.

I hope it helps you.

Best
