### ISSUE TITLE
Hide fields from the filters section

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#48]
Hi,
I want to ask you a question.
I am working on a section in which I have hidden some fields to a certain profile.
When users with the assigned profile access they do not see the fields, so far so good.
On the other hand, I have realized that in the Filters section these fields do continue to appear.
Is there a way that these fields do not appear in the filters either, adding some property or similar, without having to delete the field?

Thanks

**Comment by renderpci** [comment]
Dear Pricua

Well, it's a open discussion, but, for now, the consensus was that all users can search in any field have or have not access to read or edit it.
Why? Because the search don't have implications in data, and sometimes a admin user could configure a specific search for specific user with fields that the user can not see, edit, etc.

It could be discuss, because, it make sense that if you don't have access to a field, you might not be able to search it. But we asked about this question and the consensus was that all users should search in any field and this configuration is better than close the access.

Best
